[build-system]
build-backend = "uv_build"
requires = [ "uv_build>=0.12.5,<0.13.0" ]

[dependency-groups]
dev = [ "pyright>=1.1.411", "ruff>=0.15.13" ]

[project]
classifiers = [
  "Development Status :: 1 - Planning",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "aiohttp>=3.13.5",
  "asyncstdlib>=3.14.0",
  "humanfriendly>=10.0",
  "loguru>=0.7.3",
  "py-opensonic>=10.3.0",
  "pydantic>=2.13.4",
  "pydantic-settings>=2.14.1",
  "python-dotenv>=1.2.2",
  "stoat-py[speed,voice]>=1.2.1",
  "timezonefinder[numba]>=8.2.5",
  "tzlocal>=5.4.4",
]
description = "A tiny Stoat bot to bring social media feeds to your communities!"
license = "AGPL-3.0-or-later"
name = "ranma"
requires-python = ">=3.14"
version = "2026.8.18a"

[[project.authors]]
name = "Emily"
email = "emily@kemonomimi.moe"

[project.readme]
content-type = "text/markdown"
file = "README.md"

[project.scripts]
ranma = "ranma:entrypoint"

[project.urls]
funding = "https://emily.kemonomimi.moe#donate"
github = "https://github.com/OtakuEmily/ranma"
issues = "https://forge.kemonomimi.moe/OtakuEmily/ranma/issues"
repository = "https://forge.kemonomimi.moe/OtakuEmily/ranma.git"

[tool.pyright]
exclude = [
  "**/node_modules",
  "**/__pycache__",
  "**/.venv",
  "**/migrations"
]
include = [ "src" ]
pythonVersion = "3.14"
reportMissingTypeStubs = "none"
reportUnknownArgumentType = "none"
reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportUnusedFunction = "none"
typeCheckingMode = "strict"

[tool.ruff]
line-length = 100
src = [ "src" ]
target-version = "py314"

[tool.ruff.lint.pydocstyle]
convention = "google"
